# app_traffic_hours/models.py

from django.db import models
from app_locations.models import Locations

class TrafficHours(models.Model):
    # id_lokasi = models.ForeignKey(Locations, on_delete=models.CASCADE)
    id_lokasi = models.ForeignKey(Locations, on_delete=models.CASCADE, db_column='id_lokasi')
    jam_0 = models.IntegerField()
    jam_1 = models.IntegerField()
    jam_2 = models.IntegerField()
    jam_3 = models.IntegerField()
    jam_4 = models.IntegerField()
    jam_5 = models.IntegerField()
    jam_6 = models.IntegerField()
    jam_7 = models.IntegerField()
    jam_8 = models.IntegerField()
    jam_9 = models.IntegerField()
    jam_10 = models.IntegerField()
    jam_11 = models.IntegerField()
    jam_12 = models.IntegerField()
    jam_13 = models.IntegerField()
    jam_14 = models.IntegerField()
    jam_15 = models.IntegerField()
    jam_16 = models.IntegerField()
    jam_17 = models.IntegerField()
    jam_18 = models.IntegerField()
    jam_19 = models.IntegerField()
    jam_20 = models.IntegerField()
    jam_21 = models.IntegerField()
    jam_22 = models.IntegerField()
    jam_23 = models.IntegerField()
    tarif_0 = models.IntegerField()
    tarif_1 = models.IntegerField()
    tarif_2 = models.IntegerField()
    tarif_3 = models.IntegerField()
    tarif_4 = models.IntegerField()
    tarif_5 = models.IntegerField()
    tarif_6 = models.IntegerField()
    tarif_7 = models.IntegerField()
    tarif_8 = models.IntegerField()
    tarif_9 = models.IntegerField()
    tarif_10 = models.IntegerField()
    tarif_11 = models.IntegerField()
    tarif_12 = models.IntegerField()
    tarif_13 = models.IntegerField()
    tarif_14 = models.IntegerField()
    tarif_15 = models.IntegerField()
    tarif_16 = models.IntegerField()
    tarif_17 = models.IntegerField()
    tarif_18 = models.IntegerField()
    tarif_19 = models.IntegerField()
    tarif_20 = models.IntegerField()
    tarif_21 = models.IntegerField()
    tarif_22 = models.IntegerField()
    tarif_23 = models.IntegerField()

    class Meta:
        db_table = 'tt_data_hour'
        managed = False
